version: '2'
services:
  chronograf:
    image: quay.io/influxdb/chronograf
    container_name: chronograf
    hostname: chronograf-${HOST_HOSTNAME}
    volumes:
     - ${DATA}/chronograf/data/:/var/lib/chronograf
     - ${DATA}/chronograf/etc/:/etc/chronograf
    env_file:
      - chronograf.env
    ports:
      - "8888:8888"
    ulimits:
      nofile:
        soft: 64000
        hard: 64000

