version: '2'
services:
  grafana:
    image: grafana/grafana:${GRAFANA_TAG}
    container_name: grafana
    hostname: grafana-${HOST_HOSTNAME}
    volumes:
      - ${DATA}/grafana/sqlite:/var/lib/grafana
    env_file:
      - grafana.env
    environment:
      GF_SERVER_ROOT_URL: http://${HOST_HOSTNAME}:3000
      GF_SERVER_DOMAIN: ${HOST_HOSTNAME}
    ports:
      - "3000:3000"
