version: '2'
services:
  influxdb:
    image: influxdb:${INFLUXTAG}
    container_name: influxdb
    hostname: influxdb-${HOST_HOSTNAME}
    volumes:
      - ${DATA}/influxdb/data/:/var/lib/influxdb
      - ${DATA}/influxdb/etc/:/etc/influxdb
    env_file:
      - influxdb.env
    ports:
      - "443:8086"
    ulimits:
      nofile:
        soft: 64000
        hard: 64000

