version: '2'
services:
  kapacitor:
    image: kapacitor:${INFLUXTAG}
    container_name: kapacitor
    hostname: kapacitor-${HOST_HOSTNAME}
    volumes:
     - ${DATA}/kapacitor/data/:/var/lib/kapacitor/
     - ${DATA}/kapacitor/etc/:/etc/kapacitor
    env_file:
      - kapacitor.env
    ports:
      - "9092:9092"
    ulimits:
      nofile:
        soft: 64000
        hard: 64000

